# Generated by Django 3.2.5 on 2021-07-14 16:53

from django.db import migrations, models
import django.db.models.deletion
import recipe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=25, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('main_ingredient', models.BooleanField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=25, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to=recipe.models.get_upload_path)),
                ('description', models.CharField(max_length=255)),
                ('steps', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.CharField(default=recipe.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('fk_recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
