# Generated by Django 3.2.5 on 2021-07-14 21:10

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='slug',
            field=models.SlugField(blank=True, default=recipe.models.get_RandomString, max_length=20, unique=True),
        ),
    ]
