# Generated by Django 3.2.5 on 2021-07-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210714_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='fk_measurement_unit',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='fk_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='fk_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='fk_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='fk_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='fk_user',
            new_name='user',
        ),
    ]
