# Generated by Django 3.2.5 on 2021-08-03 20:43

from django.db import migrations, models
import django.db.models.deletion
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210714_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fk_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to=recipe.models.get_upload_path),
        ),
    ]
