# Generated by Django 3.2.5 on 2021-08-04 18:00

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20210804_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.FileField(blank=True, default='img/default.png', null=True, upload_to=recipe.models.get_upload_path),
        ),
    ]
