# Generated by Django 3.2.5 on 2021-08-04 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_recipe_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeimage',
            name='fk_recipe',
        ),
    ]
