# Generated by Django 3.2.5 on 2021-08-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_fk_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
