# Generated by Django 3.2.5 on 2021-09-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_auto_20210812_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.Ingredient', to='recipe.Product'),
        ),
    ]
