# Generated by Django 3.2.5 on 2021-09-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='product',
        ),
    ]
